optimizerSetting: SECTION
addNullFlavor: true
generateChoicesForSingleEvent: false
replaceChars:
  #German characters
  ä: ae
  Ä: Ae
  ö: oe
  Ö: OE
  ü: ue
  Ü: Ue
  ß: ss
  # Norwegian characters
  æ: ae
  ø: oe
  å: aa
